version: '3.8'

services:

  tickets-service:
    build: ./tickets_service
    container_name: tickets_service
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - net
    ports:
      - "8081:8081"
      - "8082:8082"

  booking-service:
    build: ./booking_service
    container_name: booking_service
    networks:
      - net
    ports:
      - "4848:4848"
      - "8080:8080"
      - "8181:8181"

  postgres:
    image: postgres
    container_name: main-db
    environment:
      POSTGRES_DB: "tickets_service"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    command: postgres -p 5432
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - net
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  net:

volumes:
  pg_data:
    driver: local
