#server:
#  port: 8081
#  contextPath: /api.tickets.com
server:
  ssl:
    key-store: classpath:tickets-service.jks
    key-store-password: admin_pass
    key-password: admin_pass
    key-alias: tickets-service

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/tickets_service
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop #update
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  application:
    name: tickets_service
