server:
  port: 8080
#  contextPath: /api.tickets.com

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tickets_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop #update
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  application:
    name: tickets_service
